### ISSUE TITLE
pin_code_location_dtls:

### ISSUE THREAD

**Issue by shailesh** [bombardier-gif/covid-vaccine-booking#300]
location_dtls:
+-------+---------------+-----------------+--------------+
|   idx |   district_id | district_name   |   alert_freq |
+=======+===============+=================+==============+
|     1 |           294 | BBMP            |         1100 |
+-------+---------------+-----------------+--------------+
        pin_code_location_dtls:
list index out of range
Exiting Script
sh: pause: command not found

@Nakul93

**Comment by jatinguta** [comment]
in json file it is not capturing pincode's

"pin_code_location_dtls": [],

**Comment by shailesh** [comment]
"minimum_slots": 2,
    "pin_code_location_dtls": [],
    "refresh_freq": 7,
    "search_option": 2,
    "start_date": 1,
    
    
    this is there in json even though got this error. I tried for state/disctrict not for pincodes so this error came up

**Comment by Nakul93** [comment]
Will this be fixed in #298 @BlackRider97 ?

**Comment by uvmittal** [comment]
> Will this be fixed in #298 @BlackRider97 ?

no

**Comment by SnoCold** [comment]
the PR doesn't fix the issue, it actually creates a new issue (options being referenced before initialization).. the issue is on line 220 of utils.py 

all you need to do in your files is add this line
after line 220
```
 pin_code_location_dtls = location_dtls
```

**Comment by uvmittal** [comment]
> the PR doesn't fix the issue, it actually creates a new issue (options being referenced before initialization).. the issue is on line 220 of utils.py
> 
> all you need to do in your files is add this line
> after line 220
> 
> ```
>  pin_code_location_dtls = location_dtls
> ```

can you do a pull request

**Comment by shailesh** [comment]
#300 #304

**Comment by SnoCold** [comment]
alrighty, will do

**Comment by uvmittal** [comment]
> alrighty, will do

thanks mate
please leave a link

**Comment by SnoCold** [comment]
Yes, will do that as well

**Comment by SnoCold** [comment]
please Check the PR, I have also added steps to fix for people who already created the json.

**Comment by uvmittal** [comment]
> please Check the PR, I have also added steps to fix for people who already created the json.

i tried but the issue persists
probably coz i selected 2 as aoption but still it wants pincodes

**Comment by SnoCold** [comment]
but two is hybrid, i thought there must be some other logic there. Does it work if you modify your json?

**Comment by uvmittal** [comment]
> but two is states, i thought there must be some other logic there. Does it work if you modify your json?

no

**Comment by Akash199211113** [comment]
I tried to add the code as suggested, but I am getting some error can you help me to fix
![image](https://user-images.githubusercontent.com/84634712/119327620-ca509500-bca0-11eb-8537-2d9c73fd426e.png)

**Comment by SnoCold** [comment]
> I tried to add the code as suggested, but I am getting some error can you help me to fix
> ![image](https://user-images.githubusercontent.com/84634712/119327620-ca509500-bca0-11eb-8537-2d9c73fd426e.png)

@Akash199211113

**Comment by SnoCold** [comment]
You have some extra or insufficient tabs/spaces.. it is not a code issue but a formatting issue

**Comment by Akash199211113** [comment]
Yes I edited in notepad, can u suggest me how to fix ?

**Comment by 6mxo89sqh** [comment]
#312 will fix this too.

**Comment by SnoCold** [comment]
> Yes I edited in notepad, can u suggest me how to fix ?

Just do a fresh pull/clone now
